[tools]
python = "3.13"
ansible = "latest"
"pipx:ansible-lint" = "latest"
"pipx:yamllint" = "latest"

[tasks]
lint = "just lint"
test = "just test"
build = "just build"
release = "just release-check"
